title: "Ayoub NAIT MIHOUB"
email: naitmihoub.ayoub@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ayoub NAITMIHOUB's personal website.
baseurl: "/" 
url: "https://iyy0v.github.io" 
twitter_username: AyoubNaitMihoub
github_username:  iyy0v

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
